### ISSUE TITLE
BDT application (step1_Samples preparation running problem)

### ISSUE THREAD

**Issue by gourangakole** [ExtraYukawa/Script_ForMVA#1]
while going to run:
``
python slim_mc.py 
``
I see because of some variables its crashing, not sure which one
https://github.com/ExtraYukawa/Script_ForMVA/blob/e1b540d72114ec96c7b49b73ac81474f338888c4/BDT_application/step1_Samplepreparation/slim_mc.py#L176

At least run for:
```
for c in ('ttc_region','genweight','HT','j1_pt','j1_eta','j1_phi','j1_mass','j2_pt','j2_eta','j2_phi','j2_mass','j3_pt','j3_eta','j3_phi','j3_mass','j1_FlavB','j1_FlavCvB','j1_FlavCvL','j2_FlavB','j2_FlavCvB','j2_FlavCvL','j3_FlavB','j3_FlavCvB','j3_FlavCvL','PV_npvsGood',
'PV_x','PV_y','PV_z','nSV','ttc_l1_pt','ttc_l1_eta','ttc_l1_phi','ttc_l1_mass','ttc_l2_pt','ttc_l2_eta','ttc_l2_phi','ttc_l2_mass','ttc_met','ttc_met_phi','ttc_mll','ttc_mllj1','ttc_mllj2','ttc_mllj3','puWeight','puWeightUp','puWeightDown','ttc_met_jesup','ttc_met_jesdo',
'ttc_met_jerup','ttc_met_jerdo','ttc_met_unclusterEup','ttc_met_unclusterEdo','ttc_met_phi_jesup','ttc_met_phi_jesdo','ttc_met_phi_jerup','ttc_met_phi_jerdo','ttc_met_phi_unclusterEup','ttc_met_phi_unclusterEdo','dr_j1j2','dr_j1j3','dr_j2j3','HT_jesup','HT_jesdo',
'HT_jerup','HT_jerdo','ttc_mllj1_jesup','ttc_mllj1_jesdo','ttc_mllj1_jerup','ttc_mllj1_jerdo','ttc_mllj2_jesup','ttc_mllj2_jesdo','ttc_mll2_jerup','ttc_mllj2_jerdo','ttc_mllj3_jesup','ttc_mllj3_jesdo','ttc_mllj3_jerup','ttc_mllj3_jerdo'):
```

Need more debug!

**Comment by gourangakole** [comment]
@AlbertHsuNTUphys @menglu21 If you can reproduce this:

Not sure why starting with "mu_id" crashed.

Although looking at the definition

https://github.com/ExtraYukawa/Script_ForMVA/blob/e1b540d72114ec96c7b49b73ac81474f338888c4/BDT_application/step1_Samplepreparation/slim_mc.py#L114

https://github.com/ExtraYukawa/Script_ForMVA/blob/e1b540d72114ec96c7b49b73ac81474f338888c4/BDT_application/step1_Samplepreparation/slim.h#L544-L558


Seems ok...we need to debug more.

**Comment by tihsu99** [comment]
Current issue related to muId scale factor I found is that we do not manually set muon pt when it excess the maximum value of TH2 of muon Id scale factor. This should be set to 120 GeV(maximum boundary of SF) . But, this issue seems not to lead crashed. I may also debug for this.

**Comment by gourangakole** [comment]
> Current issue related to muId scale factor I found is that we do not manually set muon pt when it excess the maximum value of TH2 of muon Id scale factor. This should be set to 120 GeV(maximum boundary of SF) . But, this issue seems not to lead crashed. I may also debug for this.

Great thanks @AlbertHsuNTUphys ...Lets see.

**Comment by tihsu99** [comment]
Hi @gourangakole , @menglu21 . Except for the pt boundary of the SF. The crush may highly related to reading the SFs from root file. Variables that need this step failed (muon ID SF, electron ID SF, trigger SF etc.). I've tested it by hand, probably the error occur in these lines. (just put "return 1.;" before or after the line and see if the code can run successfully)
https://github.com/ExtraYukawa/Script_ForMVA/blob/e1b540d72114ec96c7b49b73ac81474f338888c4/BDT_application/step1_Samplepreparation/slim.h#L549-L550
But the code seems no problem, still debugging it.

**Comment by gourangakole** [comment]
Hi @AlbertHsuNTUphys yes, good catch. May be you make a PR to those fixes. And then we have a version running. What do you think? 

But I have seen one additional problem
e.g you want to run with one variation:
```
for c in ('ttc_mllj3_jerdo') 
```
Do see that crashed as well for me.

**Comment by tihsu99** [comment]
Hi @gourangakole . Okay, I've pushed it. Only some minor changes in current stage. I found some issues that need some check and may discuss with you and Meng. The bug is still there, so I still debug for it.
On my side, I plot the histogram of each variables to see if any error occur. But ttc_mllj3_jerdo works fine in this way.

**Comment by gourangakole** [comment]
hi @AlbertHsuNTUphys 

Further input to debug, in case you have not noticed:

here:
if you keep only this function:

https://github.com/ExtraYukawa/Script_ForMVA/blob/a12c6c89f571b566bfe7b21e35ac4ef83c5fbbc1/BDT_application/step1_Samplepreparation/slim.h#L531-L541

It starts appearing that warning
``
"IncrementalExecutor::executeFunction: symbol '_ZN4ROOT4Math9GenVector5ThrowEPKc' unresolved while linking function '_GLOBAL__sub_I_cling_module_438'!"
``

and the program eventually ``crashed``:

I find this useful discussion:
https://root-forum.cern.ch/t/creating-a-column-of-std-vector-root-ptetaphievector-with-rdataframe/34151

and (its the root version may cause, I am running on CMSSW_10_6_29 which gives root v6.14

so I do not find some compatible version with python2 ...that has at least v6.16 

Maybe that can solve the problem.

NB>: with python3 there are other modules that crashed. so I do not know want more crashed now :(

**Comment by tihsu99** [comment]
Hi @gourangakole , the detailed problem is found. It's mainly due to function M() in ROOT file https://root.cern.ch/doc/master/GenVector_2PtEtaPhiE4D_8h_source.html, where it used ROOT::Math::GenVector::Throw function when the inv. mass < 0. Somehow this function is problematic in lxplus, so we encounter the error (the bug that we've discussed.). The solution is change PtEtaPhiMVector to PtEtaPhiEVector and write M() function on our own. It works fine in my code. I'll combine some change on muon ID SF (there are some mistake of the errors) and pull them together tomorrow.

**Comment by gourangakole** [comment]
> Hi @gourangakole , the detailed problem is found. It's mainly due to function M() in ROOT file https://root.cern.ch/doc/master/GenVector_2PtEtaPhiE4D_8h_source.html, where it used ROOT::Math::GenVector::Throw function when the inv. mass < 0. Somehow this function is problematic in lxplus, so we encounter the error. The solution is change PtEtaPhiMVector to PtEtaPhiEVector and write M() function on our own. It works fine in my code. I'll combine some change on muon ID SF (there are some mistake of the errors) and pull them together tomorrow.

Thank you @AlbertHsuNTUphys wow.
the problem is cluster-dependent..that's really what I did not expect tbh.

**Comment by tihsu99** [comment]
To be honest, I'm not sure whether this is cluster-dependent, but the source code seems fine in ROOT document and I can actually include the the header file it needed, but the code still can't run because that Throw() function. So, my way is just avoid using that function because it's only auxiliary, so I think it's okay.

**Comment by tihsu99** [comment]
Original way faces some trouble since we do not have jet energy variable. I didn't notice that before. There is other quick way to solve this, just not run it under CMSSW and setup the root environment to root v6.16 using following command.
`source /cvmfs/sft.cern.ch/lcg/views/LCG_95/x86_64-slc6-gcc8-opt/setup.sh`
Then it's okay to run.
(Main problem after detail thinking is due to the build up of root in lxplus. It seems that it doesn't successfully build the link of some header files like "GenVector_exception.h". That leads to some function can not run successfully. Similar problem is mentioned in https://root-forum.cern.ch/t/unresolved-while-linking/28481)

**Comment by gourangakole** [comment]
> source /cvmfs/sft.cern.ch/lcg/views/LCG_95/x86_64-slc6-gcc8-opt/setup.sh

Hi @AlbertHsuNTUphys very Good.

Yes, that is what I was saying in https://github.com/ExtraYukawa/Script_ForMVA/issues/1#issuecomment-1208015871 😄 

That root version seems the problem.  

Then one question why do we use that ``slc-6`` source root script? 
Do you find something in slc7?


https://root-forum.cern.ch/t/unresolved-while-linking/28481
I have seen this link and thought about whether any shared library is missed from Meng or not.

**Comment by tihsu99** [comment]
Oh, I think this may be better for lxplus7
`source /cvmfs/sft.cern.ch/lcg/views/LCG_96/x86_64-centos7-gcc8-opt/setup.sh`
It change to ROOT6.18, but still works.

**Comment by gourangakole** [comment]
Thanks @AlbertHsuNTUphys 
I just added that in a setup script (so that we do not forget)
1577870cadd6d71cfd9504683239ccb95c62fd5b

and added a basic readme
13d8fb29069df4812bd485c926abdb3f93fe6c08

**Comment by gourangakole** [comment]
IncrementalExecutor::executeFunction: symbol '_ZN4ROOT4Math9GenVector5ThrowEPKc' unresolved while linking function '_GLOBAL__sub_I_cling_module_438'!
You are probably missing the definition of ROOT::Math::GenVector::Throw(char const*)
Maybe you need to load the corresponding shared library?
('Processing ', 'WWZ.root')

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 2 (Thread 0x7f601e800700 (LWP 21655)):
#0  0x00007f6030d72b3b in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007f6030d72bcf in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007f6030d72c6b in sem_wait

GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x00007f60310c9cf8 in PyThread_acquire_lock (lock=lock
entry=0xffd6d0, waitflag=waitflag
entry=1) at Python/thread_pthread.h:324
#4  0x00007f6031086286 in PyEval_RestoreThread (tstate=tstate
entry=0x44671e0) at Python/ceval.c:359
#5  0x00007f6020baabd4 in floatsleep (secs=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_6_0_pre4-slc7_amd64_gcc700/build/CMSSW_10_6_0_pre4-build/BUILD/slc7_amd64_gcc700/external/python/2.7.14-pafccj/python-2.7.14/Modules/timemodule.c:1057
#6  time_sleep (self=<optimized out>, args=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_6_0_pre4-slc7_amd64_gcc700/build/CMSSW_10_6_0_pre4-build/BUILD/slc7_amd64_gcc700/external/python/2.7.14-pafccj/python-2.7.14/Modules/timemodule.c:206
#7  0x00007f603108fe56 in call_function (oparg=<optimized out>, pp_stack=0x7f601e7ff5d0) at Python/ceval.c:4357
#8  PyEval_EvalFrameEx (f=f
entry=0x7f6020bdf410, throwflag=throwflag
entry=0) at Python/ceval.c:2994
#9  0x00007f6031090b68 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals
entry=0x0, args=args
entry=0x7f6020bd5168, argcount=<optimized out>, kws=kws
entry=0x7f6031346068, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3589
#10 0x00007f6031006dad in function_call (func=0x7f6020c36f50, arg=0x7f6020bd5150, kw=0x7f6020bd0168) at Objects/funcobject.c:523
#11 0x00007f6030fd6f73 in PyObject_Call (func=func
entry=0x7f6020c36f50, arg=arg
entry=0x7f6020bd5150, kw=kw
entry=0x7f6020bd0168) at Objects/abstract.c:2547
#12 0x00007f6031089479 in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, pp_stack=0x7f601e7ff848, func=0x7f6020c36f50) at Python/ceval.c:4671
#13 PyEval_EvalFrameEx (f=f
entry=0x7f6020bdd770, throwflag=throwflag
entry=0) at Python/ceval.c:3033
#14 0x00007f603108f437 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7f601e7ff950, func=<optimized out>) at Python/ceval.c:4442
#15 call_function (oparg=<optimized out>, pp_stack=0x7f601e7ff950) at Python/ceval.c:4377
#16 PyEval_EvalFrameEx (f=f
entry=0x7f6018000910, throwflag=throwflag
entry=0) at Python/ceval.c:2994
#17 0x00007f603108f437 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7f601e7ffa60, func=<optimized out>) at Python/ceval.c:4442
#18 call_function (oparg=<optimized out>, pp_stack=0x7f601e7ffa60) at Python/ceval.c:4377
#19 PyEval_EvalFrameEx (f=f
entry=0x7f6030258c90, throwflag=throwflag
entry=0) at Python/ceval.c:2994
#20 0x00007f6031090b68 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals
entry=0x0, args=args
entry=0x7f6020bd5128, argcount=<optimized out>, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3589
#21 0x00007f6031006cd9 in function_call (func=0x7f6020bdb2a8, arg=0x7f6020bd5110, kw=0x0) at Objects/funcobject.c:523
#22 0x00007f6030fd6f73 in PyObject_Call (func=func
entry=0x7f6020bdb2a8, arg=arg
entry=0x7f6020bd5110, kw=kw
entry=0x0) at Objects/abstract.c:2547
#23 0x00007f6030fe5d1c in instancemethod_call (func=0x7f6020bdb2a8, arg=0x7f6020bd5110, kw=0x0) at Objects/classobject.c:2600
#24 0x00007f6030fd6f73 in PyObject_Call (func=func
entry=0x7f6030285820, arg=arg
entry=0x7f6031346050, kw=<optimized out>) at Objects/abstract.c:2547
#25 0x00007f6031086937 in PyEval_CallObjectWithKeywords (func=0x7f6030285820, arg=0x7f6031346050, kw=<optimized out>) at Python/ceval.c:4226
#26 0x00007f60310cfec2 in t_bootstrap (boot_raw=0x445c660) at ./Modules/threadmodule.c:620
#27 0x00007f6030d6cea5 in start_thread () from /lib64/libpthread.so.0
#28 0x00007f603038cb0d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f6031386740 (LWP 21630)):
#0  0x00007f6030353659 in waitpid () from /lib64/libc.so.6
#1  0x00007f60302d0f62 in do_system () from /lib64/libc.so.6
#2  0x00007f60302d1311 in system () from /lib64/libc.so.6
#3  0x00007f602ece508d in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#4  0x00007f602ece7934 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#5  <signal handler called>
#6  0x00007f602e4aed74 in ?? ()
#7  0x00007ffee0524200 in ?? ()
#8  0x000000000b5b55e0 in ?? ()
#9  0x00007ffee05241f0 in ?? ()
#10 0x00007f600a97c76c in ?? ()
#11 0x0000000012d26a10 in ?? ()
#12 0x000000000b5b55e0 in ?? ()
#13 0x0000000010371620 in ?? ()
#14 0x00007ffee0524260 in ?? ()
#15 0x0000000000001b21 in ?? ()
#16 0x000000000b4f04b0 in ?? ()
#17 0x0000000006e36a40 in ?? ()
#18 0x00007f602ffdbb39 in ROOT::Internal::TTreeReaderValueBase::GetAddress() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libTreePlayer.so
#19 0x00007f600a915438 in ?? ()
#20 0x00000000075d0850 in ?? ()
#21 0x000000000b5b55e0 in ?? ()
#22 0x3f80000010371620 in ?? ()
#23 0xbfac200000000001 in ?? ()
#24 0xbf42c0004282fd11 in ?? ()
#25 0x0000000042c91433 in ?? ()
#26 0x00007ffee05242a0 in ?? ()
#27 0x00007f60053e0352 in ?? ()
#28 0x00000000075d0850 in ?? ()
#29 0x00000000075d02c0 in ?? ()
#30 0x00000000075cf210 in ?? ()
#31 0x00000000075cec80 in ?? ()
#32 0x00000000075cc470 in ?? ()
#33 0x000000000f9316e8 in ?? ()
#34 0x00007ffee0524320 in ?? ()
#35 0x00007f60053e02bf in ?? ()
#36 0x000000001093d230 in ?? ()
#37 0x00007f60053e0300 in ?? ()
#38 0x00000000075d02c0 in ?? ()
#39 0x00000000075cf210 in ?? ()
#40 0x00000000075cec80 in ?? ()
#41 0x00000000075cc470 in ?? ()
#42 0x000000000f9316e8 in ?? ()
#43 0x000000000f931690 in ?? ()
#44 0x0000000000000000 in ?? ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f602e4aed74 in ?? ()
#7  0x00007ffee0524200 in ?? ()
#8  0x000000000b5b55e0 in ?? ()
#9  0x00007ffee05241f0 in ?? ()
#10 0x00007f600a97c76c in ?? ()
#11 0x0000000012d26a10 in ?? ()
#12 0x000000000b5b55e0 in ?? ()
#13 0x0000000010371620 in ?? ()
#14 0x00007ffee0524260 in ?? ()
#15 0x0000000000001b21 in ?? ()
#16 0x000000000b4f04b0 in ?? ()
#17 0x0000000006e36a40 in ?? ()
#18 0x00007f602ffdbb39 in ROOT::Internal::TTreeReaderValueBase::GetAddress() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libTreePlayer.so
#19 0x00007f600a915438 in ?? ()
#20 0x00000000075d0850 in ?? ()
#21 0x000000000b5b55e0 in ?? ()
#22 0x3f80000010371620 in ?? ()
#23 0xbfac200000000001 in ?? ()
#24 0xbf42c0004282fd11 in ?? ()
#25 0x0000000042c91433 in ?? ()
#26 0x00007ffee05242a0 in ?? ()
#27 0x00007f60053e0352 in ?? ()
#28 0x00000000075d0850 in ?? ()
#29 0x00000000075d02c0 in ?? ()
#30 0x00000000075cf210 in ?? ()
#31 0x00000000075cec80 in ?? ()
#32 0x00000000075cc470 in ?? ()
#33 0x000000000f9316e8 in ?? ()
#34 0x00007ffee0524320 in ?? ()
#35 0x00007f60053e02bf in ?? ()
#36 0x000000001093d230 in ?? ()
#37 0x00007f60053e0300 in ?? ()
#38 0x00000000075d02c0 in ?? ()
#39 0x00000000075cf210 in ?? ()
#40 0x00000000075cec80 in ?? ()
#41 0x00000000075cc470 in ?? ()
#42 0x000000000f9316e8 in ?? ()
#43 0x000000000f931690 in ?? ()
#44 0x0000000000000000 in ?? ()
===========================================================


Traceback (most recent call last):
  File "slim_mc.py", line 190, in <module>
    Slim_module(iin,ntemp*0.5,'dummy',True)
  File "slim_mc.py", line 178, in Slim_module
    dOut.Snapshot(treeOut,fileOut,columns)
TypeError: none of the 3 overloaded methods succeeded. Full details:
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RJittedFilter,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    problem in C++; program state has been reset
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RJittedFilter,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, basic_string_view<char,char_traits<char> > columnNameRegexp = "", const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    could not convert argument 3
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RJittedFilter,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, initializer_list<string> columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    could not convert argument 3

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f6030353659 in waitpid () from /lib64/libc.so.6
#1  0x00007f60302d0f62 in do_system () from /lib64/libc.so.6
#2  0x00007f60302d1311 in system () from /lib64/libc.so.6
#3  0x00007f602ece508d in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#4  0x00007f602ece7934 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#5  <signal handler called>
#6  0x00007f602ebbc923 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#7  0x00007f602f323ccc in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libRIO.so
#8  0x00007f602eb188c1 in (anonymous namespace)::R__ListSlowClose(TList*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#9  0x00007f602eb19a0d in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#10 0x00007f602eb1a112 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#11 0x00007f601da1502a in ?? ()
#12 0x0000000000000000 in ?? ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f602ebbc923 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#7  0x00007f602f323ccc in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libRIO.so
#8  0x00007f602eb188c1 in (anonymous namespace)::R__ListSlowClose(TList*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#9  0x00007f602eb19a0d in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#10 0x00007f602eb1a112 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/external/slc7_amd64_gcc700/lib/libCore.so
#11 0x00007f601da1502a in ?? ()
#12 0x0000000000000000 in ?? ()
===========================================================


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/python/2.7.14-pafccj/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.14.09-pafccj6/lib/ROOT.py", line 814, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/python/2.7.14-pafccj/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.14.09-pafccj6/lib/ROOT.py", line 814, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset

**Comment by gourangakole** [comment]
closing this one :)
